version: 2

updates:
  - package-ecosystem: npm
    directory: "/client"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    groups:
      client_deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/server"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    groups:
      server_deps:
        patterns:
          - "*"
